export const COUNTRIES = [
  { code: 'us', name: 'United States', flag: '🇺🇸' },
  { code: 'gb', name: 'United Kingdom', flag: '🇬🇧' },
  { code: 'ca', name: 'Canada', flag: '🇨🇦' },
  { code: 'au', name: 'Australia', flag: '🇦🇺' },
  { code: 'de', name: 'Germany', flag: '🇩🇪' },
  { code: 'fr', name: 'France', flag: '🇫🇷' },
  { code: 'es', name: 'Spain', flag: '🇪🇸' },
  { code: 'it', name: 'Italy', flag: '🇮🇹' },
  { code: 'jp', name: 'Japan', flag: '🇯🇵' },
  { code: 'br', name: 'Brazil', flag: '🇧🇷' },
  { code: 'mx', name: 'Mexico', flag: '🇲🇽' },
  { code: 'in', name: 'India', flag: '🇮🇳' },
  { code: 'ar', name: 'Argentina', flag: '🇦🇷' },
  { code: 'be', name: 'Belgium', flag: '🇧🇪' },
  { code: 'ch', name: 'Switzerland', flag: '🇨🇭' },
  { code: 'cl', name: 'Chile', flag: '🇨🇱' },
  { code: 'co', name: 'Colombia', flag: '🇨🇴' },
  { code: 'dk', name: 'Denmark', flag: '🇩🇰' },
  { code: 'fi', name: 'Finland', flag: '🇫🇮' },
  { code: 'gr', name: 'Greece', flag: '🇬🇷' },
  { code: 'hk', name: 'Hong Kong', flag: '🇭🇰' },
  { code: 'ie', name: 'Ireland', flag: '🇮🇪' },
  { code: 'il', name: 'Israel', flag: '🇮🇱' },
  { code: 'kr', name: 'South Korea', flag: '🇰🇷' },
  { code: 'nl', name: 'Netherlands', flag: '🇳🇱' },
  { code: 'no', name: 'Norway', flag: '🇳🇴' },
  { code: 'nz', name: 'New Zealand', flag: '🇳🇿' },
  { code: 'pe', name: 'Peru', flag: '🇵🇪' },
  { code: 'ph', name: 'Philippines', flag: '🇵🇭' },
  { code: 'pl', name: 'Poland', flag: '🇵🇱' },
  { code: 'pt', name: 'Portugal', flag: '🇵🇹' },
  { code: 'ru', name: 'Russia', flag: '🇷🇺' },
  { code: 'se', name: 'Sweden', flag: '🇸🇪' },
  { code: 'sg', name: 'Singapore', flag: '🇸🇬' },
  { code: 'th', name: 'Thailand', flag: '🇹🇭' },
  { code: 'tr', name: 'Turkey', flag: '🇹🇷' },
  { code: 'za', name: 'South Africa', flag: '🇿🇦' },
];
